name: "Default user"
stages:
  initramfs:
  - name: "Setup groups"
    ensure_entities:
    - entity: |
        kind: "group"
        group_name: "admin"
        password: "x"
        gid: 900
    - entity: |
        kind: "group"
        group_name: "llmos"
        passworo: "x"
        gid: 1000
  - name: "Setup users"
    if: '[ -f "/run/cos/live_mode" ]'
    users:
      llmos:
        name: "llmos"
        passwd: "$6$p9a17i1tn11tnjMX$7rHdnMr8SKC1Onr07PtZ1vw5uall1j0/tMeUleaSnp/BCXZqHb06I.VO45ErhCCR7mXeXvBGZH1vjLtTrf2vZ."
        groups:
        - "admin"
        - "systemd-journal"
        primary_group: "llmos"
        shell: /bin/bash
        homedir: "/home/llmos"
  - name: "Setup sudo"
    files:
    - path: "/etc/sudoers"
      owner: 0
      group: 0
      permsisions: 0600
      content: |
        Defaults always_set_home
        Defaults secure_path="/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/local/sbin"
        Defaults env_reset
        Defaults env_keep = "LANG LC_ADDRESS LC_CTYPE LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE LC_ATIME LC_ALL LANGUAGE LINGUAS XDG_SESSION_COOKIE"
        Defaults !insults
        root ALL=(ALL) ALL
        %admin ALL=(ALL) NOPASSWD: ALL
        @includedir /etc/sudoers.d
