version: 2

env:
  - REGISTRY={{ if index .Env "REGISTRY"  }}{{ .Env.REGISTRY }}{{ end }}
  - BUILDER={{ if index .Env "BUILDER"  }}{{ .Env.BUILDER }}{{ else }}default{{ end }}
  - VERSION={{ if index .Env "VERSION"  }}{{ .Env.VERSION }}{{ end }}
  - COMMIT={{ if index .Env "COMMIT"  }}{{ .Env.COMMIT }}{{ end }}

snapshot:
  # https://goreleaser.com/customization/snapshots/
  name_template: '{{ trimprefix .Summary "v" }}'

checksum:
  # https://goreleaser.com/customization/checksum/
  name_template: 'checksums.txt'
  algorithm: sha256

release:
  draft: true
  
archives:
  - id: "default"
    format: 'binary'
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

builds:
  - id: "llmos"
    binary: llmos
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - netgo
    ldflags:
      - -s
      - -w
      - -X "github.com/llmos-ai/llmos/version/version.Version={{ .Env.VERSION }}"
      - -X "github.com/llmos-ai/llmos/version/version.Commit={{ .Env.COMMIT }}"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: package/Dockerfile-cli
    image_templates:
      - "{{ .Env.REGISTRY }}/llmos-cli:{{ .Env.VERSION }}-amd64"
    build_flag_templates:
      - "--builder={{ .Env.BUILDER }}"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Env.VERSION}}"
      - "--label=org.opencontainers.image.source=https://github.com/llmos-ai/llmos"
      - "--platform=linux/amd64"

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: package/Dockerfile-cli
    image_templates:
      - "{{ .Env.REGISTRY }}/llmos-cli:{{ .Env.VERSION }}-arm64"
    build_flag_templates:
      - "--builder={{ .Env.BUILDER }}"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Env.VERSION}}"
      - "--label=org.opencontainers.image.source=https://github.com/llmos-ai/llmos"
      - "--platform=linux/arm64"

docker_manifests:
  - use: docker
    name_template: "{{ .Env.REGISTRY }}/llmos-cli:{{ .Env.VERSION }}"
    image_templates:
      - "{{ .Env.REGISTRY }}/llmos-cli:{{ .Env.VERSION }}-amd64"
      - "{{ .Env.REGISTRY }}/llmos-cli:{{ .Env.VERSION }}-arm64"

dist: dist/cli
