#!/bin/bash
set -e

. /etc/os-release

IMAGE=$(echo "$IMAGE" | sed 's![/:]!-!g')

mkdir -p /etc/rancher/k3s/config.yaml.d
cat > /etc/rancher/k3s/config.yaml.d/99-llmos-labels.yaml << EOF
node-label+:
- llmos.ai/managed=true
- llmos.ai/image=${IMAGE}
- llmos.ai/image-tag=${IMAGE_TAG}
EOF
