#!/bin/bash
set -e -x

cd $(dirname $0)/..

dist_dir=dist/artifacts
## create dist dir if not exist
if [ ! -d "${dist_dir}" ]; then
  mkdir -p "${dist_dir}"
fi

function package_images() {
  airgap_image_file='scripts/airgap/image-list.txt'
  images=$(cat "${airgap_image_file}")
  xargs -n1 docker pull <<< "${images}"
  docker save ${images} -o dist/artifacts/llmos-airgap-images-${TARGETARCH}.tar
  zstd -T0 -16 -f --long=25 dist/artifacts/llmos-airgap-images-${TARGETARCH}.tar -o dist/artifacts/llmos-airgap-images-${TARGETARCH}.tar.zst
  if [ ${TARGETARCH} = amd64 ]; then
    cp "${airgap_image_file}" dist/artifacts/llmos-images.txt
  fi
}

function download_tarballs() {
  airgap_tarball_file='scripts/airgap/tarball-list.txt'
  tarballs=$(envsubst < "${airgap_tarball_file}")
  echo "${tarballs}"
  xargs -n1 curl -sfL -O --output-dir dist/artifacts <<< "${tarballs}"
  echo "Created tarball"
}

function download_ollama() {
  echo "Downloading ollama ${OLLAMA_VERSION} for ${TARGETARCH}"
  curl -sfL https://ollama.com/download/ollama-linux-${TARGETARCH}?version=${OLLAMA_VERSION} -o dist/artifacts/ollama
}

package_images
download_tarballs
download_ollama
