ARG OS_IMAGE
ARG FLAVOR
ARG ARCH
ARG VERSION
ARG OUTPUT_DIR="/output"
ARG PROJECT_PREFIX="LLMOS"

FROM ${OS_IMAGE} AS iso
ARG FLAVOR
ARG ARCH
ARG VERSION
ARG OUTPUT_DIR
ARG PROJECT_PREFIX
ENV ISO_PREFIX="${PROJECT_PREFIX}-${FLAVOR}-${ARCH}"

COPY iso/manifest.yaml manifest.yaml

RUN elemental --debug --config-dir . build-iso \
    -o ${OUTPUT_DIR} -n ${ISO_PREFIX}  dir:/

# Extract the squashfs image for PXE boot
RUN xorriso -osirrox on -indev ${OUTPUT_DIR}/${ISO_PREFIX}.iso -extract /rootfs.squashfs ${OUTPUT_DIR}/${PROJECT_PREFIX}-rootfs-${ARCH}.squashfs


FROM scratch as final
ARG OUTPUT_DIR

COPY --from=iso ${OUTPUT_DIR} /
COPY --from=iso /boot/initrd /
COPY --from=iso /boot/vmlinuz /
